// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/ljb/suosi/dumi2/node_modules/.pnpm/dumi@2.0.10_400f05c017d466529a53122e54bf08a6/node_modules/dumi/dist/client/theme-api/index.js';
